### PR TITLE
Fix writing multiple tracks to file

### PR DESCRIPTION
**Pull request by tmwsnrx**
Fixes jcelerier/libremidi#63

### CODE REVIEW

**Comment by jcelerier** [comment]
hey! thanks for the patch, this looks good, you thinh you could add a test case? e.g. which writes a file, then loads it and checks that the tracks are there?

**Comment by jcelerier** [comment]
for instance by making an "integration" folder with integration tests that would more or less look like https://github.com/jcelerier/libremidi/blob/master/tests/unit/midifile_write.cpp

**Comment by tmwsnrx** [comment]
Sure, I'll add one. Might just take a day or two

**Comment by tmwsnrx** [comment]
Okay, I added a test case. @jcelerier will this suffice?

**Review by jcelerier — COMMENTED** [review]
looks perfect, just waiting for CI to pass :)

**Comment by jcelerier** [comment]
thanks!

**Pull request merged**
